### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by Kawa-oneechan** [Kawa-oneechan/Asspull3X-roms#2]
### Miscellaneous
- [ ] Improve navigator.
- [ ] Consider integrating navigator into BIOS?
- [ ] Consider further worth of command line — NC style combination?

### Sokoban
- [ ] Ending screen image.
- [ ] Inbetween animations, both walking and pushing.
- [ ] Different tilesets, rotating every *n* levels.
- [ ] Status line?
- [ ] More/better music — what we have now *will* get annoying.

### Snake
- [ ] *Nibbles* style level progression, perhaps as a separate mode.
- [ ] Connected snake instead of balls — check MS *Rattler Race*?
- [ ] Better title screen?

### Misc game ideas
- Horizontal shooter a la *Gradius*. Suggested names "Salanyander" and "Farahmander".
- Platform game. Not likely for Kawa to do, code-wise.
